<?php
/**
 * Created by PhpStorm.
 * User: lenovo
 * Date: 31.12.2017
 * Time: 20:35
 */

namespace app\components;

use yii\base\Widget;
use app\models\Category;

/**
 * Class MenuWidget
 * @package app\components
 */
class MenuWidget extends Widget
{

    public $tpl;
    public $data;
    public $tree;
    public $menuHtml;

    public function  init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->tpl === null){
            $this->tpl == 'menu';
        }
        $this->tpl .= '.php';
    }

    /**
     * @return string
     */
    public function run()
    {
        $this->data = Category::find()->indexBy('id')->asArray()->all();
        $this->tree = $this->getTree();
        debug($this->tree);
        return $this->tpl;
        //parent::run(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function getTree()
    {

        $tree  = [];
        foreach ($this->data as $id => &$node){
            if(!$node['parent_id']){
                $tree[$id] = &$node;
            }
            else {
                $this->data[$node['parent_id']]['childs'][$node['id']] = &$node;
            }
        }
        return $tree;
    }

}