<?php
/**
 * Created by PhpStorm.
 * User: lenovo
 * Date: 31.12.2017
 * Time: 20:35
 */

namespace app\components;

use yii\base\Widget;

/**
 * Class MenuWidget
 * @package app\components
 */
class MenuWidget extends Widget
{

    public $tpl;

    public function  init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->tpl === null){
            $this->tpl == 'menu';
        }
        $this->tpl .= '.php';
    }

    /**
     * @return string
     */
    public function run()
    {
        return $this->tpl;
        //parent::run(); // TODO: Change the autogenerated stub
    }


}