<?php
/**
 * Created by PhpStorm.
 * User: lenovo
 * Date: 31.12.2017
 * Time: 20:35
 */

namespace app\components;

use yii\base\Widget;
use app\models\Category;
use Yii;
/**
 * Class MenuWidget
 * @package app\components
 */
class MenuWidget extends Widget
{

    public $tpl;
    public $data;
    public $tree;
    public $menuHtml;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->tpl === null) {
            $this->tpl == 'menu';
        }
        $this->tpl .= '.php';
    }

    /**
     * @return string
     */
    public function run()
    {
        //get cache
        $menu = Yii::$app->cache->get('menu');
        if($menu) return $menu;

        $this->data = Category::find()->indexBy('id')->asArray()->all();
        $this->tree = $this->getTree();
        $this->menuHtml = $this->getMenuHtml($this->tree);
        //set cache
        Yii::$app->cache->set('menu', $this->menuHtml, 3600);
        return $this->menuHtml;
        //parent::run(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function getTree()
    {
        $tree = [];
        foreach ($this->data as $id => &$node) {
            if (!$node['parent_id']) {
                $tree[$id] = &$node;
            } else {
                $this->data[$node['parent_id']]['childs'][$node['id']] = &$node;
            }
        }
        return $tree;
    }

    /**
     * @param $tree
     * @return string
     */
    protected function getMenuHtml($tree)
    {
        $str = '';
        foreach ($tree as $category) {
            $str .= $this->catToTemplate($category);
        }
        return $str;
    }

    /**
     * @param $category
     * @return string
     */
    protected function catToTemplate($category)
    {
        ob_start();
        include __DIR__ . '/menu_tpl/' . $this->tpl;
        return ob_get_clean();
    }

}